services:
    rmcgirr83.topicrestriction.listener:
        class: rmcgirr83\topicrestriction\event\listener
        arguments:
            - '@auth'
            - '@language'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
